## Import numpy library and Define arrays

In [5]:
import numpy as np

In [34]:
# Defind a array and specify data type for this as int 32 bit
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [16]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [21]:
# Get Dimension
a.ndim

1

In [25]:
# Get Shape
b.shape

(2, 3)

In [35]:
# Get Type
a.dtype

dtype('int32')

In [36]:
b.dtype

dtype('float64')

In [37]:
# Get Size
a.itemsize

4

In [38]:
# Get total size
a.nbytes

12