## Accessing/Changing specific elements, row, columns etc

In [1]:
import numpy as np

In [43]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 13]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 13]]


In [46]:
# Get a specitfic element [r, c]
a[1, 5]

13

In [50]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
# Get a specific column
a[: , 2]

array([ 3, 10])

In [54]:
# Getting a little more fancy [start index(inclusive) : end index(exclusive) : step size]
a[0, 1:6:2]

array([2, 4, 6])

In [62]:
# Setting a value at a specific position [r, c]
a[1, 5] = 20
print(a)

a[:, 2] = np.array([50, 51])
print(a)


[[ 1  2 50  4  5  6  7]
 [ 8  9 51 11 12 20 13]]
[[ 1  2 50  4  5  6  7]
 [ 8  9 51 11 12 20 13]]


In [73]:
b = np.array([ [[1, 2], [3,4]], [[5, 6], [7,8]] ])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [74]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [77]:
b[ :, 1, :]

array([[9, 9],
       [8, 8]])

In [76]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
